set_property PACKAGE_PIN P17 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk ]

set_property PACKAGE_PIN K2 [get_ports success]
set_property IOSTANDARD LVCMOS33 [get_ports success ]
set_property PACKAGE_PIN J2 [get_ports failure]
set_property IOSTANDARD LVCMOS33 [get_ports failure ]

set_property PACKAGE_PIN R15 [get_ports enter]
set_property IOSTANDARD LVCMOS33 [get_ports enter ]
set_property PACKAGE_PIN N4 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset ]

set_property PACKAGE_PIN G6 [get_ports {wm[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {wm[0]}]
set_property PACKAGE_PIN E1 [get_ports {wm[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {wm[1]}]
set_property PACKAGE_PIN F1 [get_ports {wm[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {wm[2]}]
set_property PACKAGE_PIN G1 [get_ports {wm[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {wm[3]}]

set_property PACKAGE_PIN D2 [get_ports {dm[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dm[0]}]
set_property PACKAGE_PIN E2 [get_ports {dm[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dm[1]}]
set_property PACKAGE_PIN F3 [get_ports {dm[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dm[2]}]
set_property PACKAGE_PIN F4 [get_ports {dm[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dm[3]}]
set_property PACKAGE_PIN D3 [get_ports {dm[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dm[4]}]
set_property PACKAGE_PIN E3 [get_ports {dm[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dm[5]}]
set_property PACKAGE_PIN D4 [get_ports {dm[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dm[6]}]
set_property PACKAGE_PIN H2 [get_ports {dm[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dm[7]}]

set_property PACKAGE_PIN V1 [get_ports left]
set_property IOSTANDARD LVCMOS33 [get_ports left]
set_property PACKAGE_PIN R11 [get_ports right]
set_property IOSTANDARD LVCMOS33 [get_ports right]
set_property PACKAGE_PIN U4 [get_ports up]
set_property IOSTANDARD LVCMOS33 [get_ports up]
set_property PACKAGE_PIN R17 [get_ports down]
set_property IOSTANDARD LVCMOS33 [get_ports down]


set_property PACKAGE_PIN B2 [get_ports {countdowndm[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {countdowndm[0]}]
set_property PACKAGE_PIN B3 [get_ports {countdowndm[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {countdowndm[1]}]
set_property PACKAGE_PIN A1 [get_ports {countdowndm[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {countdowndm[2]}]
set_property PACKAGE_PIN B1 [get_ports {countdowndm[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {countdowndm[3]}]
set_property PACKAGE_PIN A3 [get_ports {countdowndm[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {countdowndm[4]}]
set_property PACKAGE_PIN A4 [get_ports {countdowndm[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {countdowndm[5]}]
set_property PACKAGE_PIN B4 [get_ports {countdowndm[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {countdowndm[6]}]

set_property PACKAGE_PIN H1 [get_ports {countdownwm[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {countdownwm[0]}]
set_property PACKAGE_PIN C1 [get_ports {countdownwm[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {countdownwm[1]}]
set_property PACKAGE_PIN C2 [get_ports {countdownwm[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {countdownwm[2]}]
set_property PACKAGE_PIN G2 [get_ports {countdownwm[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {countdownwm[3]}]

set_property PACKAGE_PIN F6 [get_ports {stateLED[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {stateLED[0]}]
set_property PACKAGE_PIN G4 [get_ports {stateLED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {stateLED[1]}]
set_property PACKAGE_PIN G3 [get_ports {stateLED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {stateLED[2]}]
set_property PACKAGE_PIN J4 [get_ports {stateLED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {stateLED[3]}]

